FROM ykode/crosstool

LABEL maintainer="Didiet Noor <dnoor@ykode.id>"

ADD configurations/silvermont.ctconfig ct-build/.config 

RUN cd ct-build \
    && ../crosstool-ng/ct-build source \
    && cd ..